global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - '/etc/prometheus/rules/alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Мониторинг хоста (CPU, RAM, Disk, Network)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'monitoring-host'

  # Мониторинг Docker контейнеров
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'docker-containers'

  # Мониторинг Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana_monitoring:3200']
    metrics_path: '/metrics'
    scheme: 'http'
    basic_auth:
      username: 'admin'
      password: 'admin'

  # Мониторинг Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
